name: CI/CD - Build & Push

on:
  push:
    branches: [ "main" ]   
  workflow_dispatch:      

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & Push Docker Image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./WebBeeShop         
          file: ./WebBeeShop/Dockerfile  
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/beeshop-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/beeshop-web:${{ github.sha }}
